book/urls.py
from . import views
from django.urls import include, path
app_name='book'
urlpatterns = [
    path('',views.view_book,name='view'),
    path('create_book_form/',views.create_book_form,name='create_book_form'),
    path('save_book/',views.save_book,name='save_book'),
    path('update_book_form/(?P<ISBN>\D+)',views.update_book_form,name='update_book_form'),
    path('update_book/',views.update_book,name='update_book'),
    path('delete/(?P<ISBN>\D+)',views.delete_book,name='delete_book'),



    path('view_bookItem/',views.view_bookItem,name='view_bookItem'),
    path('create_bookItem_form/',views.create_bookItem_form,name='create_bookItem_form'),
    path('save_bookItem/',views.save_bookItem,name='save_bookItem'),
    path('update_bookItem_form/(?P<ID>\D+)',views.update_bookItem_form,name='update_bookItem_form'),
    path('update_bookItem/',views.update_bookItem,name='update_bookItem'),
    path('delete_bookItem/(?P<ID>\D+)',views.delete_bookItem,name='delete_bookItem'),




    path('view_bookStats/',views.view_bookStats,name='view_bookStats'),
    path('create_bookStats_form/',views.create_bookStats_form,name='create_bookStats_form'),
    path('save_bookStats/',views.save_bookStats,name='save_bookStats'),
    path('update_bookStats_form/(?P<ID>\D+)',views.update_bookStats_form,name='update_bookStats_form'),
    path('update_bookStats/',views.update_bookStats,name='update_bookStats'),
    path('delete_bookStats/(?P<ID>\D+)',views.delete_bookStats,name='delete_bookStats'),



    # path('view_author/',views.view_author,name='view_author'),
    # path('create_author_form/',views.create_author_form,name='create_author_form'),
    # path('save_author/',views.save_author,name='save_author'),
    # path('update_author_form/(?P<ID>\D+)',views.update_author_form,name='update_author_form'),
    # path('update_author/',views.update_author,name='update_author'),
    # path('delete_author/(?P<ID>\D+)',views.delete_author,name='delete_author'),



    # path('view_publisher/',views.view_publisher,name='view_publisher'),
    # path('create_publisher_form/',views.create_publisher_form,name='create_publisher_form'),
    # path('save_publisher/',views.save_publisher,name='save_publisher'),
    # path('update_publisher_form/(?P<ID>\D+)',views.update_publisher_form,name='update_publisher_form'),
    # path('update_publisher/',views.update_publisher,name='update_publisher'),
    # path('delete_publisher/(?P<ID>\D+)',views.delete_publisher,name='delete_publisher'),




    # path('view_category/',views.view_category,name='view_category'),
    # path('create_category_form/',views.create_category_form,name='create_category_form'),
    # path('save_category/',views.save_category,name='save_category'),
    # path('update_category_form/(?P<ID>\D+)',views.update_category_form,name='update_category_form'),
    # path('update_category/',views.update_category,name='update_category'),
    # path('delete_category/(?P<ID>\D+)',views.delete_category,name='delete_category'),

]

clothes/urls.py
from . import views
from django.urls import include, path
app_name='clothes'
urlpatterns = [
    path('',views.view_clothes,name='view_clothes'),
    path('create_clothes_form/',views.create_clothes_form,name='create_clothes_form'),
    path('save_clothes/',views.save_clothes,name='save_clothes'),
    path('update_clothes_form/(?P<ID>/D+)',views.update_clothes_form,name='update_clothes_form'),
    path('update_clothes/',views.update_clothes,name='update_clothes'),
    path('delete/(?P<ID>\D+)',views.delete_clothes,name='delete_clothes'),
]

tmdt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include("book.urls")),
    path('clothes/', include("clothes.urls")),
]

clothes/models.py
from django.db import models

# Create your models here.
class ClothesBrand(models.Model):
    ID=models.IntegerField(primary_key=True)
    name=models.TextField()
    createAt=models.DateField()
    def __str__(self):
        return self.name

class Clothes(models.Model):
    ID=models.IntegerField(primary_key=True)
    type=models.TextField(max_length=255)
    description=models.TextField()
    material=models.TextField(max_length=255)
    color=models.TextField(max_length=100)
    gender=models.TextField(max_length=100)
    size=models.TextField(max_length=10)
    name=models.TextField(max_length=255)
    season=models.TextField(max_length=100)
    img=models.ImageField(upload_to = 'pictures', null=True, blank=True)
    clothesBrand=models.ForeignKey(ClothesBrand,on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class ClothesItem(models.Model):
    ID=models.IntegerField(primary_key=True)
    barcode=models.TextField()
    price=models.FloatField()
    discount=models.FloatField()
    clothes=models.OneToOneField(Clothes,on_delete=models.CASCADE)
    def __str__(self):
        return self.barcode
        
class ClothesStats(models.Model):
    ID=models.IntegerField(primary_key=True)
    barcode=models.TextField()
    quantity=models.IntegerField()
    importPrice=models.FloatField()
    quantityLeft=models.IntegerField()
    createAt=models.DateField()
    clothes=models.ForeignKey(Clothes ,on_delete=models.CASCADE)
    def __str__(self):
        return str(self.ID)

clothes/forms.py
from django import forms  
from clothes.models import Clothes, ClothesItem, ClothesBrand, ClothesStats
class ClothesForm(forms.ModelForm):  
    class Meta:  
        model = Clothes
        fields = "__all__" 

class ClothesItemForm(forms.ModelForm):  
    class Meta:  
        model = ClothesItem 
        fields = "__all__" 

class ClothesBrandForm(forms.ModelForm):  
    class Meta:  
        model = ClothesBrand
        fields = "__all__" 
class ClothesStatsForm(forms.ModelForm):  
    class Meta:  
        model = ClothesStats
        fields = "__all__" 
        

clothes/views.py
import http
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from clothes.models import Clothes
from clothes.forms import ClothesForm

def view_clothes(request):
    ctx={}
    clotheses=Clothes.objects.all()
    print(clotheses)
    ctx["clotheses"]=clotheses
    return render(request,"clothes/view_clothes.html",ctx)

def create_clothes_form(request):
    ctx={}
    ctx["form"]=ClothesForm(request.POST or None)
    return render(request,"clothes/create_clothes_form.html",ctx)

def save_clothes(request):
    if(request.method=="POST"):
        form=ClothesForm(request.POST,request.FILES)
        if(form.is_valid):
            form.save()
            return view_clothes(request)
    return HttpResponse("That bai")    
def update_clothes_form(request,ID):
    ctx = {}
    obj=get_object_or_404(Clothes,ID =ID)
    form = ClothesForm(instance=obj)
    ctx["form"] = form
    return render(request,"update_clothes_form.html", ctx) 

def update_clothes(request):
    ctx = {}
    
    form = ClothesForm(request.POST,request.FILES)
    obj=get_object_or_404(Clothes,ID =form["ID"].value())
    form.instance = obj
    if(form.is_valid):
        form.save()
        return view_clothes(request)
    ctx["form"] = form
    return render(request,"update_clothes_form.html", ctx) 

def delete_clothes(request,ID):
    obj=get_object_or_404(Clothes,ID=ID)
    if(request.method =="POST"):
        obj.delete()
        return render(request,"clothes/view_clothes.html")
    return HttpResponse("That bai")

















from clothes.models import ClothesItem
from clothes.forms import ClothesItemForm
def view_clothesItem(request):
    ctx={}
    clothesItems=ClothesItem.objects.all()
    ctx["clothesItems"]=clothesItems
    return render(request,"clothes/view_clothesItem.html",ctx)
def create_clothesItem_form(request):
    ctx={}
    ctx["form"]=ClothesItemForm(request.POST or None)
    return render(request,"clothes/create_clothesItem_form.html",ctx)
def save_clothesItem(request):
    if(request.method=="POST"):
        form=ClothesItemForm(request.POST,request.FILES)
        if(form.is_valid):
            form.save()
            return render(request,"clothes/view_clothesItem.html")
    return HttpResponse("That bai")    
def update_clothesItem_form(request,ID):
    obj=get_object_or_404(Clothes,ID=ID)
    ctx={}
    ctx["form"]=ClothesItemForm(request.POST or None,instance=obj)
    return render(request,"clothes/update_clothesItem_form.html",ctx)     
def delete_clothes(request,ID):
    obj=get_object_or_404(Clothes,ID=ID)
    if(request.method =="POST"):
        obj.delete()
        return render(request,"clothes/view_clothes.html")
    return HttpResponse("That bai")

clothes/templates/clothes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- bootstrap core css -->


  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2.5">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <h2>Book</h2>
          <li><a href="{% url 'book:view' %}">Manage books</a></li>
          <li><a href="{% url 'book:view_bookItem' %}">Manage book item</a></li>
          <li><a href="{% url 'book:view_bookStats' %}">Manage book statistic</a></li>
          <!-- <li><a href="books">Manage books</a></li>
          <li><a href="authors">Manage authors</a></li>
          <li><a href="">Manage publisher</a></li>
          <li><a href="">Manage category</a></li>
          <li><a href="">Manage book item</a></li>
          <li><a href="">Manage book statistic</a></li> -->
        </ul>
        <br>
        <ul class="sidebar-nav">
          <h2>Clothes</h2>
          <li><a href="{% url 'clothes:view_clothes' %}">Manage clothes</a></li>
          <li><a href="">Manage clothes brand</a></li>
          <li><a href="">Manage clothes item</a></li>
          <li><a href="">Manage clothes statistic</a></li>
        </ul>
        <ul class="sidebar-nav">
          <h2>Smart device</h2>
          <li><a href="">Manage mobile phone</a></li>
          <li><a href="">Manage laptop</a></li>
          <li><a href="">Manage smart device brand</a></li>
          <li><a href="">Manage smart device statistic</a></li>
          <li><a href="">Manage smart device item</a></li>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

clothes/templates/clothes/create_clothes_form.html
{% extends "base.html" %}
{% block content %}

<form method="POST"   action="{% url 'clothes:save_clothes' %}"    enctype="multipart/form-data">
    
    {% csrf_token %}
    
    {{ form.as_p }}
     
    <input type="submit" value="Submit">
</form>

{% endblock %}

clothes/templates/clothes/create_clothesitem_form.html
<form method="POST"   action="{% url 'clothes:save_clothesItem' %}"    enctype="multipart/form-data">
    
    {% csrf_token %}
    
    {{ form.as_p }}
     
    <input type="submit" value="Submit">
</form>

clothes/templates/clothes/update_clothes_form.html
{% extends "base.html" %}
{% block content %}

<form method="POST"   action="{% url 'clothes:update_clothes' %}"    enctype="multipart/form-data">
    
    {% csrf_token %}
    
    {{ form.as_p }}
     
    <input type="submit" value="Submit">
</form>

{% endblock %}

clothes/templates/clothes/update_clothesitem_form.html
<form method="POST"   action="{% url 'clothes:save_clothesItem' %}"    enctype="multipart/form-data">
    
    {% csrf_token %}
    
    {{ form.as_p }}
     
    <input type="submit" value="Submit">
</form>

clothes/templates/clothes/view_clothes.html
{% extends "base.html" %}
{% block content %}

<style>
    table,
    th,
    td {
        border: 2px double;
        text-align: center;
        text-transform: uppercase;
    }

    table {
        width: 100%;
        background-color: beige;
    }
    
</style>
<div>
    <table>
        <tr>
            <th>ID</th>
            <th>type</th>
            <th>description</th>
            <th>material</th>
            <th>color</th>
            <th>gender</th>
            <th>size</th>
            <th>name</th>
            <th>season</th>
            <th>img</th>
            <th>clothes Brand</th>
        </tr>

        {% for clothes in clotheses %}
        <tr>
            <td>{{clothes.ID}}</td>
            <td>{{clothes.type}}</td>
            <td>{{clothes.description}}</td>
            <td>{{clothes.material}}</td>
            <td>{{clothes.color}}</td>
            <td>{{clothes.gender}}</td>
            <td>{{clothes.size}}</td>
            <td>{{clothes.name}}</td>
            <td>{{clothes.season}}</td>
            <td><img src="{{clothes.img}}" alt=""></td>
            <td>{{clothes.clothesBrand.name}}</td>
            
            
            <td>
                <form action="{% url 'clothes:update_clothes_form' clothes.ID %}" method="GET">
                    {% csrf_token %}
                    <input type="submit" value="Update">
                </form>
                <form action="{% url 'clothes:delete_clothes' clothes.ID %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Delete">
                </form>
            </td>
        </tr>
        {% endfor %}

    </table>
</div>

{% endblock %}

clothes/templates/clothes/view_clothesitem.html
<style>
    table,
    th,
    td {
        border: 1px solid;
        text-align: center;
        text-transform: uppercase;
    }

    table {
        width: 100%;
        background-color: beige;
    }
</style>
<div>
    <table>
        <tr>
            <th>ISBN</th>
            <th>title</th>
            <th>numberOfPage</th>
            <th>language</th>
            <th>img</th>
            <th>publisher</th>
            <th>category</th>
            <th>author</th>
            <th>action</th>
        </tr>


        {% for clothes in clothess %}
        <tr>
            <td>{{clothes.ISBN}}</td>
            <td>{{clothes.title}}</td>
            <td>{{clothes.numberOfPage}}</td>
            <td>{{clothes.language}}</td>
            <td><img src="{{clothes.img}}" alt=""></td>
            <td>{{clothes.publisher.name}}</td>
            <td>{{clothes.category.name}}</td>
            <td>{{clothes.author.name}}</td>
            <td>
                <form action="{% url 'clothes:update_clothes_form' clothes.ISBN %}" method="GET">
                    {% csrf_token %}
                    <input type="submit" value="Update">
                </form>
                <form action="{% url 'clothes:delete_clothes' clothes.ISBN %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Delete">
                </form>
            </td>
        </tr>
        {% endfor %}

    </table>
</div>