book/urls.py
from . import views
from django.urls import include, path
app_name='book'
urlpatterns = [
    path('',views.view_book,name='view'),
    path('create_book_form/',views.create_book_form,name='create_book_form'),
    path('save_book/',views.save_book,name='save_book'),
    path('update_book_form/(?P<ISBN>\D+)',views.update_book_form,name='update_book_form'),
    path('update_book/',views.update_book,name='update_book'),
    path('delete/(?P<ISBN>\D+)',views.delete_book,name='delete_book'),



    path('view_bookItem/',views.view_bookItem,name='view_bookItem'),
    path('create_bookItem_form/',views.create_bookItem_form,name='create_bookItem_form'),
    path('save_bookItem/',views.save_bookItem,name='save_bookItem'),
    path('update_bookItem_form/(?P<ID>\D+)',views.update_bookItem_form,name='update_bookItem_form'),
    path('update_bookItem/',views.update_bookItem,name='update_bookItem'),
    path('delete_bookItem/(?P<ID>\D+)',views.delete_bookItem,name='delete_bookItem'),




    path('view_bookStats/',views.view_bookStats,name='view_bookStats'),
    path('create_bookStats_form/',views.create_bookStats_form,name='create_bookStats_form'),
    path('save_bookStats/',views.save_bookStats,name='save_bookStats'),
    path('update_bookStats_form/(?P<ID>\D+)',views.update_bookStats_form,name='update_bookStats_form'),
    path('update_bookStats/',views.update_bookStats,name='update_bookStats'),
    path('delete_bookStats/(?P<ID>\D+)',views.delete_bookStats,name='delete_bookStats'),



    # path('view_author/',views.view_author,name='view_author'),
    # path('create_author_form/',views.create_author_form,name='create_author_form'),
    # path('save_author/',views.save_author,name='save_author'),
    # path('update_author_form/(?P<ID>\D+)',views.update_author_form,name='update_author_form'),
    # path('update_author/',views.update_author,name='update_author'),
    # path('delete_author/(?P<ID>\D+)',views.delete_author,name='delete_author'),



    # path('view_publisher/',views.view_publisher,name='view_publisher'),
    # path('create_publisher_form/',views.create_publisher_form,name='create_publisher_form'),
    # path('save_publisher/',views.save_publisher,name='save_publisher'),
    # path('update_publisher_form/(?P<ID>\D+)',views.update_publisher_form,name='update_publisher_form'),
    # path('update_publisher/',views.update_publisher,name='update_publisher'),
    # path('delete_publisher/(?P<ID>\D+)',views.delete_publisher,name='delete_publisher'),




    # path('view_category/',views.view_category,name='view_category'),
    # path('create_category_form/',views.create_category_form,name='create_category_form'),
    # path('save_category/',views.save_category,name='save_category'),
    # path('update_category_form/(?P<ID>\D+)',views.update_category_form,name='update_category_form'),
    # path('update_category/',views.update_category,name='update_category'),
    # path('delete_category/(?P<ID>\D+)',views.delete_category,name='delete_category'),

]

tmdt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include("book.urls")),
    path('clothes/', include("clothes.urls")),
]

book/models.py
from distutils.command.upload import upload
from django.db import models
from django.forms import DateField

# Create your models here.

class Publisher(models.Model):
    ID=models.IntegerField(primary_key=True)
    name=models.TextField()
    address=models.TextField()
    def __str__(self):
        return self.name
class Category(models.Model):
    ID=models.IntegerField(primary_key=True)
    name=models.TextField()
    createAt=DateField()
    def __str__(self):
        return self.name
class Author(models.Model):
    ID=models.IntegerField(primary_key=True)
    name=models.TextField()
    biography=models.TextField()
    def __str__(self):
        return self.name
class Book(models.Model):
    ISBN=models.CharField(max_length=255)
    title=models.TextField()
    numberOfPage=models.IntegerField()
    language=models.TextField()
    img=models.ImageField(upload_to = 'pictures', null=True, blank=True)
    publisher=models.ForeignKey(Publisher ,on_delete=models.CASCADE)
    category=models.ForeignKey(Category ,on_delete=models.CASCADE)
    author=models.ForeignKey(Author ,on_delete=models.CASCADE)

    def __str__(self):
        return self.title
class BookItem(models.Model):
    ID=models.IntegerField(primary_key=True)
    barcode=models.TextField()
    price=models.FloatField()
    discount=models.FloatField()
    # book=models.ForeignKey(Book, unique=True,on_delete=models.CASCADE)
    book=models.OneToOneField(Book,on_delete=models.CASCADE)
    def __str__(self):
        return self.barcode
class BookStats(models.Model):
    ID=models.IntegerField(primary_key=True)
    quantity=models.IntegerField()
    importPrice=models.FloatField()
    quantityLeft=models.IntegerField()
    createAt=models.DateField()
    book=models.ForeignKey(Book ,on_delete=models.CASCADE)
    def __str__(self):
        return str(self.ID)

book/forms.py
from django import forms  
from book.models import Book 
class BookForm(forms.ModelForm):  
    class Meta:  
        model = Book  
        fields = "__all__" 



from book.models import BookItem
class BookItemForm(forms.ModelForm):  
    class Meta:  
        model = BookItem 
        fields = "__all__" 


from book.models import BookStats
class BookStatsForm(forms.ModelForm):  
    class Meta:  
        model = BookStats
        fields = "__all__" 




from book.models import Author
class AuthorForm(forms.ModelForm):  
    class Meta:  
        model = Author
        fields = "__all__" 




from book.models import Category
class CategoryForm(forms.ModelForm):  
    class Meta:  
        model = Category
        fields = "__all__" 





from book.models import Publisher
class PublisherForm(forms.ModelForm):  
    class Meta:  
        model = Publisher
        fields = "__all__" 

book/views.py
import http
from django.shortcuts import get_object_or_404, render,redirect
from django.http import HttpResponse
from book.models import Book
from book.forms import BookForm

def view_book(request):
    ctx={}
    books=Book.objects.all()
    print(books)
    ctx["books"]=books
    return render(request,"book/view_book.html",ctx)
def create_book_form(request):
    ctx={}
    ctx["form"]=BookForm(request.POST or None)
    return render(request,"book/create_book_form.html",ctx)
def save_book(request):
    if(request.method=="POST"):
        form=BookForm(request.POST,request.FILES)
        if(form.is_valid):
            form.save()
            return render(request,"book/view_book.html")
    return HttpResponse("That bai")    
def update_book_form(request,ISBN):
    print(ISBN)
    obj=get_object_or_404(Book,ISBN=ISBN)
    ctx={}
    ctx["form"]=BookForm(request.POST or None,instance=obj)
    return render(request,"book/update_book_form.html",ctx)   
def update_book(request):
    form=BookForm(request.POST,request.FILES)
    obj=get_object_or_404(Book,ISBN=form["ISBN"].value())
    form.instance=obj
    if(form.is_valid):
        form.save();
        return view_book(request)
    return render(request,"book/view_book.html")      
def delete_book(request,ISBN):
    obj=get_object_or_404(Book,ISBN=ISBN)
    if(request.method =="POST"):
        obj.delete()
        return view_book(request)
    return HttpResponse("That bai")

















from book.models import BookItem
from book.forms import BookItemForm
def view_bookItem(request):
    ctx={}
    bookItems=BookItem.objects.all()
    ctx["bookItems"]=bookItems
    return render(request,"book/view_bookItem.html",ctx)
def create_bookItem_form(request):
    ctx={}
    ctx["form"]=BookItemForm(request.POST or None)
    return render(request,"book/create_bookItem_form.html",ctx)
def save_bookItem(request):
    if(request.method=="POST"):
        form=BookItemForm(request.POST,request.FILES)
        if(form.is_valid):
            form.save();
            return view_bookItem(request)
    return HttpResponse("That bai")    
def update_bookItem_form(request,ID):
    obj=get_object_or_404(BookItem,ID=ID)
    ctx={}
    ctx["form"]=BookItemForm(request.POST or None,instance=obj)
    return render(request,"book/update_bookItem_form.html",ctx) 
def update_bookItem(request):
    form=BookItemForm(request.POST,request.FILES)
    obj=get_object_or_404(BookItem,ID=form["ID"].value())
    form.instance=obj
    if(form.is_valid):
        form.save();
        return view_bookItem(request)
    return render(request,"book/view_bookItem.html")    
def delete_bookItem(request,ID):
    obj=get_object_or_404(BookItem,ID=ID)
    if(request.method =="POST"):
        obj.delete()
        return view_bookItem(request)
    return HttpResponse("That bai")





























from book.models import BookStats
from book.forms import BookStatsForm
def view_bookStats(request):
    ctx={}
    bookStatss=BookStats.objects.all()
    ctx["bookStatss"]=bookStatss
    return render(request,"book/view_bookStats.html",ctx)
def create_bookStats_form(request):
    ctx={}
    ctx["form"]=BookStatsForm(request.POST or None)
    return render(request,"book/create_bookStats_form.html",ctx)
def save_bookStats(request):
    if(request.method=="POST"):
        form=BookStatsForm(request.POST,request.FILES)
        if(form.is_valid):
            form.save();
            return view_bookStats(request)
    return HttpResponse("That bai")    
def update_bookStats_form(request,ID):
    obj=get_object_or_404(BookStats,ID=ID)
    ctx={}
    ctx["form"]=BookStatsForm(request.POST or None,instance=obj)
    return render(request,"book/update_bookStats_form.html",ctx) 
def update_bookStats(request):
    form=BookStatsForm(request.POST,request.FILES)
    obj=get_object_or_404(BookStats,ID=form["ID"].value())
    form.instance=obj
    if(form.is_valid):
        form.save();
        return view_bookStats(request)
    return render(request,"book/view_bookStats.html")    
def delete_bookStats(request,ID):
    obj=get_object_or_404(BookStats,ID=ID)
    if(request.method =="POST"):
        obj.delete()
        return view_bookStats(request)
    return HttpResponse("That bai")




























































# from book.models import Publisher
# from book.forms import PublisherForm
# def view_publisher(request):
#     ctx={}
#     publishers=Publisher.objects.all()
#     ctx["publishers"]=publishers
#     return render(request,"book/view_publisher.html",ctx)
# def create_publisher_form(request):
#     ctx={}
#     ctx["form"]=PublisherForm(request.POST or None)
#     return render(request,"book/create_publisher_form.html",ctx)
# def save_publisher(request):
#     if(request.method=="POST"):
#         form=PublisherForm(request.POST,request.FILES)
#         if(form.is_valid):
#             form.save();
#             return view_publisher(request)
#     return HttpResponse("That bai")    
# def update_publisher_form(request,ID):
#     obj=get_object_or_404(Publisher,ID=ID)
#     ctx={}
#     ctx["form"]=PublisherForm(request.POST or None,instance=obj)
#     return render(request,"book/update_publisher_form.html",ctx) 
# def update_publisher(request):
#     form=PublisherForm(request.POST,request.FILES)
#     obj=get_object_or_404(Publisher,ID=form["ID"].value())
#     form.instance=obj
#     if(form.is_valid):
#         form.save();
#         return view_publisher(request)
#     return render(request,"book/view_publisher.html")    
# def delete_publisher(request,ID):
#     obj=get_object_or_404(Publisher,ID=ID)
#     if(request.method =="POST"):
#         obj.delete()
#         return view_publisher(request)
#     return HttpResponse("That bai")




























# from book.models import Category
# from book.forms import CategoryForm
# def view_category(request):
#     ctx={}
#     categorys=Category.objects.all()
#     ctx["categorys"]=categorys
#     return render(request,"book/view_category.html",ctx)
# def create_category_form(request):
#     ctx={}
#     ctx["form"]=CategoryForm(request.POST or None)
#     return render(request,"book/create_category_form.html",ctx)
# def save_category(request):
#     if(request.method=="POST"):
#         form=CategoryForm(request.POST,request.FILES)
#         if(form.is_valid):
#             form.save();
#             return view_category(request)
#     return HttpResponse("That bai")    
# def update_category_form(request,ID):
#     obj=get_object_or_404(Category,ID=ID)
#     ctx={}
#     ctx["form"]=CategoryForm(request.POST or None,instance=obj)
#     return render(request,"book/update_category_form.html",ctx) 
# def update_category(request):
#     form=CategoryForm(request.POST,request.FILES)
#     obj=get_object_or_404(Category,ID=form["ID"].value())
#     form.instance=obj
#     if(form.is_valid):
#         form.save();
#         return view_category(request)
#     return render(request,"book/view_category.html")    
# def delete_category(request,ID):
#     obj=get_object_or_404(Category,ID=ID)
#     if(request.method =="POST"):
#         obj.delete()
#         return view_category(request)
#     return HttpResponse("That bai")






























# from book.models import Author
# from book.forms import AuthorForm
# def view_author(request):
#     ctx={}
#     authors=Author.objects.all()
#     ctx["authors"]=authors
#     return render(request,"book/view_author.html",ctx)
# def create_author_form(request):
#     ctx={}
#     ctx["form"]=AuthorForm(request.POST or None)
#     return render(request,"book/create_author_form.html",ctx)
# def save_author(request):
#     if(request.method=="POST"):
#         form=AuthorForm(request.POST,request.FILES)
#         if(form.is_valid):
#             form.save();
#             return view_author(request)
#     return HttpResponse("That bai")    
# def update_author_form(request,ID):
#     obj=get_object_or_404(Author,ID=ID)
#     ctx={}
#     ctx["form"]=AuthorForm(request.POST or None,instance=obj)
#     return render(request,"book/update_author_form.html",ctx) 
# def update_author(request):
#     form=AuthorForm(request.POST,request.FILES)
#     obj=get_object_or_404(Author,ID=form["ID"].value())
#     form.instance=obj
#     if(form.is_valid):
#         form.save();
#         return view_author(request)
#     return render(request,"book/view_author.html")    
# def delete_author(request,ID):
#     obj=get_object_or_404(Author,ID=ID)
#     if(request.method =="POST"):
#         obj.delete()
#         return view_author(request)
#     return HttpResponse("That bai")

book/templates/book/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- bootstrap core css -->
  <style>
    *{
      font-family: 'Times New Roman', Times, serif;
    }
  </style>

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="bg-warning text-center text-capitalize">Store of Nguyen Duy Thanh</div>
  <div class="container-fluid m-1">
    <div class="row">
      <div class="col-sm-2" >
      {% block sidebar %}
        <ul class="list-group">
          <h2 class="badge-danger active text-center text-uppercase badge-pill text-capitalize font-weight-light">Book</h2>
          <li class="list-group-item"><a class="btn btn-outline-primary w-100 text-capitalize" href="{% url 'book:view' %}">Manage books</a></li>
          <li class="list-group-item"><a class="btn btn-outline-primary w-100 text-capitalize" href="{% url 'book:view_bookItem' %}">Manage book item</a></li>
          <li class="list-group-item"><a class="btn btn-outline-primary w-100 text-capitalize" href="{% url 'book:view_bookStats' %}">Manage book statistic</a></li>
          <li class="list-group-item"><a class="btn btn-outline-primary w-100 text-capitalize" href="">Manage book statistic</a></li>
        </ul>
        <br>
        <ul class="list-group">
          <h2 class="badge-danger active text-center text-uppercase badge-pill text-capitalize font-weight-light">Clothes</h2>
          <li class="list-group-item"><a class="btn btn-outline-primary w-100 text-capitalize" href="">Manage clothes</a></li>
          <li class="list-group-item"><a class="btn btn-outline-primary w-100 text-capitalize" href="">Manage clothes brand</a></li>
          <li class="list-group-item"><a class="btn btn-outline-primary w-100 text-capitalize" href="">Manage clothes item</a></li>
          <li class="list-group-item"><a class="btn btn-outline-primary w-100 text-capitalize" href="">Manage clothes statistic</a></li>
        </ul>
        <ul class="list-group">
          <h2 class="badge-danger active text-center text-uppercase badge-pill text-capitalize font-weight-light">Smart device</h2>
          <li class="list-group-item"><a class="btn btn-outline-primary w-100 text-capitalize" href="">Manage mobile phone</a></li>
          <li class="list-group-item"><a class="btn btn-outline-primary w-100 text-capitalize" href="">Manage laptop</a></li>
          <li class="list-group-item"><a class="btn btn-outline-primary w-100 text-capitalize" href="">Manage smart device brand</a></li>
          <li class="list-group-item"><a class="btn btn-outline-primary w-100 text-capitalize" href="">Manage smart device statistic</a></li>
          <li class="list-group-item"><a class="btn btn-outline-primary w-100 text-capitalize" href="">Manage smart device item</a></li>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 container-fluid " style="background-color: aqua;">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

book/templates/book/create_author_form.html
{% extends "base.html" %}
{% block content %}



<form method="POST"   action="{% url 'book:save_author' %}"    enctype="multipart/form-data">
    
    {% csrf_token %}
    
    {{ form.as_p }}
     
    <input type="submit" value="Submit">
</form>


{% endblock %}

book/templates/book/create_bookItem_form.html
{% extends "base.html" %}
{% block content %}


<form method="POST"   action="{% url 'book:save_bookItem' %}"    enctype="multipart/form-data">
    
    {% csrf_token %}
    
    {{ form.as_p }}
     
    <input type="submit" value="Submit">
</form>

{% endblock %}

book/templates/book/create_bookStats_form.html
{% extends "base.html" %}
{% block content %}

<form method="POST"   action="{% url 'book:save_bookStats' %}"    enctype="multipart/form-data">
    
    {% csrf_token %}
    
    {{ form.as_p }}
     
    <input type="submit" value="Submit">
</form>

{% endblock %}

book/templates/book/create_category_form.html
{% extends "base.html" %}
{% block content %}



<form method="POST"   action="{% url 'book:save_category' %}"    enctype="multipart/form-data">
    
    {% csrf_token %}
    
    {{ form.as_p }}
     
    <input type="submit" value="Submit">
</form>


{% endblock %}

book/templates/book/create_publisher_form.html
{% extends "base.html" %}
{% block content %}



<form method="POST"   action="{% url 'book:save_publisher' %}"    enctype="multipart/form-data">
    
    {% csrf_token %}
    
    {{ form.as_p }}
     
    <input type="submit" value="Submit">
</form>


{% endblock %}

book/templates/book/update_author_form.html
{% extends "base.html" %}
{% block content %}

<form method="POST"   action="{% url 'book:update_author' %}"    enctype="multipart/form-data">
    
    {% csrf_token %}
    
    {{ form.as_p }}
     
    <input type="submit" value="Submit">
</form>

{% endblock %}

book/templates/book/update_book_form.html
{% extends "base.html" %}
{% block content %}

<form method="POST"   action="{% url 'book:update_book' %}"    enctype="multipart/form-data">
    
    {% csrf_token %}
    
    {{ form.as_p }}
     
    <input type="submit" value="Submit">
</form>

{% endblock %}

book/templates/book/update_category_form.html
{% extends "base.html" %}
{% block content %}

<form method="POST"   action="{% url 'book:update_category' %}"    enctype="multipart/form-data">
    
    {% csrf_token %}
    
    {{ form.as_p }}
     
    <input type="submit" value="Submit">
</form>

{% endblock %}

book/templates/book/update_publisher_form.html
{% extends "base.html" %}
{% block content %}

<form method="POST"   action="{% url 'book:update_publisher' %}"    enctype="multipart/form-data">
    
    {% csrf_token %}
    
    {{ form.as_p }}
     
    <input type="submit" value="Submit">
</form>

{% endblock %}

book/templates/book/view_author.html
{% extends "base.html" %}
{% block content %}
<header>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- bootstrap core css -->


  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</header>
<style>
    /* table,
    th,
    td {
        border: 2px double;
        text-align: center;
        text-transform: uppercase;
    }

    table {
        width: 100%;
        background-color: beige;
    } */
    
</style>
<a href="{% url 'book:create_author_form' %}">Create Book</a>
<div>
    
    <table class="table table-bordered table-hover table-primary table-striped">
        <tr class="thead-dark text-capitalize text-center">
            <th>ID</th>
            <th>name</th>
            <th>biography</th>
            <th>action</th>
        </tr>


        {% for author in authors %}
        <tr>
            

            <td>{{author.ID}}</td>
            <td>{{author.name}}</td>
            <td>{{author.biography}}</td>


            <td>
                <form action="{% url 'book:update_author_form' author.ID %}" method="GET">
                    {% csrf_token %}
                    <input type="submit" value="Update" class="btn btn-outline-info w-75">
                </form>
                <form action="{% url 'book:delete_author' author.ID %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Delete" class="btn btn-outline-danger w-75">
                </form>
            </td>
        </tr>
        {% endfor %}

    </table>
</div>

{% endblock %}

book/templates/book/view_book.html
{% extends "base.html" %}
{% block content %}

<a href="{% url 'book:create_book_form' %} " class="btn btn-outline-danger w-25 mt-5 mb-5 active" style="margin-left: 75%;" >Create Book</a>
<div>
    
    <table class="table table-hover table-striped table-light">
        <tr class="thead-dark text-capitalize text-center">
            <th>ISBN</th>
            <th>title</th>
            <th>numberOfPage</th>
            <th>language</th>
            <th>img</th>
            <th>publisher</th>
            <th>category</th>
            <th>author</th>
            <th>action</th>
        </tr>


        {% for book in books %}
        {% load static %}
        <tr>
            <td>{{book.ISBN}}</td>
            <td>{{book.title}}</td>
            <td>{{book.numberOfPage}}</td>
            <td>{{book.language}}</td>
            <td><img src="../../static/2_kH1MA3M.jpg" alt="Not found"></td>
            <td>{{book.publisher.name}}</td>
            <td>{{book.category.name}}</td>
            <td>{{book.author.name}}</td>
            <td>
                <form action="{% url 'book:update_book_form' book.ISBN %}" method="GET">
                    {% csrf_token %}
                    <input type="submit" value="Update" class="btn btn-outline-info w-75 mb-1">
                </form>
                <form action="{% url 'book:delete_book' book.ISBN %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Delete" class="btn btn-outline-danger w-75">
                </form>
            </td>
        </tr>
        {% endfor %}

    </table>
</div>

{% endblock %}

book/templates/book/view_bookStats.html
{% extends "base.html" %}
{% block content %}

<style>
    table,
    th,
    td {
        border: 1px solid;
        text-align: center;
        text-transform: uppercase;
    }

    table {
        width: 100%;
        background-color: beige;
    }
</style>
<div>
    <table>
        <tr>
            <th>ID</th>
            <th>quantity</th>
            <th>importPrice</th>
            <th>quantityLeft</th>
            <th>createAt</th>
            <th>book</th>
        </tr>
        {% for bookStats in bookStatss %}
        <tr>
            <td>{{bookStats.ID}}</td>
            <td>{{bookStats.quantity}}</td>
            <td>{{bookStats.importPrice}}</td>
            <td>{{bookStats.quantityLeft}}</td>
            <td>{{bookStats.createAt}}</td>
            <td>{{bookStats.book}}</td>
            <td>
                <form action="{% url 'book:update_bookStats_form' bookStats.ID %}" method="GET">
                    {% csrf_token %}
                    <input type="submit" value="Update">
                </form>
                <form action="{% url 'book:delete_bookStats' bookStats.ID %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Delete">
                </form>
            </td>
        </tr>
        {% endfor %}

    </table>
</div>

{% endblock %}

book/templates/book/view_publisher.html
{% extends "base.html" %}
{% block content %}

<style>
    table,
    th,
    td {
        border: 2px double;
        text-align: center;
        text-transform: uppercase;
    }

    table {
        width: 100%;
        background-color: beige;
    }
</style>
<a href="{% url 'book:create_publisher_form' %}">Create Book</a>
<div>
    
    <table>
        <tr>
            <th>ID</th>
            <th>name</th>
            <th>address</th>
            <th>action</th>
        </tr>


        {% for publisher in publishers %}
        <tr>
            

            <td>{{publisher.ID}}</td>
            <td>{{publisher.name}}</td>
            <td>{{publisher.address}}</td>


            <td>
                <form action="{% url 'book:update_publisher_form' publisher.ID %}" method="GET">
                    {% csrf_token %}
                    <input type="submit" value="Update">
                </form>
                <form action="{% url 'book:delete_publisher' publisher.ID %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Delete">
                </form>
            </td>
        </tr>
        {% endfor %}

    </table>
</div>

{% endblock %}